spring.datasource.url=jdbc:postgresql://localhost:5432/attendance
spring.datasource.username=attendance_user
spring.datasource.password=attendance_pass
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080


logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.web.cors.allowed-origins=http://localhost:5173
